version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: suzan97/client:v1
    container_name: frontendcontainer
    ports:
      -'8000:8000'
    networks:
      - suzan97-network
    depends_on:
      - mongo-db

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: suzan97/backend:v1
    container_name: backendcontainer
    ports:
      -'5000:50000'
    networks:
      - suzan97-network
    depends_on:
      - mongo-db

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    volumes:
      - mongo_db:/data/db
    ports:
      -'27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME: user
      - MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - suzan97-network
    

networks:
  suzan97-network:
  driver: bridge

volumes:
  mongo_db: {}


  

