apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo
    component: back
spec:
  selector:
  matchLabel:
    app: yolo
  replica: 3
  specs:
    containers:
      - name: yolo
        image: suzan97/backend:v1
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
spec:
  selector:
    app: yolo-backend
  ports:
    - protocol: TCP
      port: 5000
  
