apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo
    component: back
spec:
  selector:
    matchLabels:
      app: yolo
  replicas: 3
  template:
    metadata:
      labels:
        app: yolo
        component: back
  spec:
    containers:
      - name: yolo
        image: suzan97/backend:v1
        ports:
          - containerPort: 5000


  
