apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  labels:
    app: yolo
    component: back
spec:
  selector:
  matchLabel:
    app: yolo
  replica: 3
  template:
    metadata:
      labels:
        app:yolo
  specs:
    containers:
      - name: yolo
        image: suzan97/client:v1
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
spec:
  type: LoadBalancer
  selector:
    app: yolo-frontend
  ports:
    - port: 3000
      protocol: TCP
      
 
