apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
        component: frontend
    spec:
      containers:
        - name: frontendyolo
          image: suewaf/yolo-frontend:yolo-frontend
          tty: true
          ports:
            - containerPort: 3000
              protocol: TCP
          resource:
          command: ["npm", "start"]

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
spec:
  type: LoadBalancer
  selector:
    app: yolo-frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
      
 
